import LegalLayout from '@/components/LegalLayout';
import Link from 'next/link';

export const metadata = {
  title: 'Shipping Policy — Back2Me Global',
  description: 'Back2Me Global shipping policy for physical product orders and Mail-It-Back label facilitation.',
};

const s = {
  page: { background: '#fff', padding: '60px 0 80px' },
  prose: { maxWidth: '760px' },
  h2: { fontSize: '1.35rem', fontWeight: '800', color: 'var(--navy)', margin: '40px 0 10px', letterSpacing: '-0.3px' },
  h3: { fontSize: '1.05rem', fontWeight: '700', color: 'var(--navy)', margin: '24px 0 8px' },
  p: { fontSize: '0.96rem', lineHeight: '1.8', color: '#374151', marginBottom: '14px' },
  ul: { paddingLeft: '20px', marginBottom: '14px' },
  li: { fontSize: '0.96rem', lineHeight: '1.8', color: '#374151', marginBottom: '4px' },
  updated: { fontSize: '0.82rem', color: 'var(--gray-text)', marginBottom: '36px', display: 'block' },
  divider: { border: 'none', borderTop: '1px solid var(--border-gray)', margin: '40px 0' },
  table: { width: '100%', borderCollapse: 'collapse', marginBottom: '20px', fontSize: '0.9rem' },
  th: { background: 'var(--off-white)', padding: '10px 14px', textAlign: 'left', fontWeight: '700', color: 'var(--navy)', border: '1px solid var(--border-gray)' },
  td: { padding: '10px 14px', border: '1px solid var(--border-gray)', color: '#374151', lineHeight: '1.6' },
  callout: { background: '#FFF7ED', border: '1px solid #FED7AA', borderRadius: '8px', padding: '16px 20px', marginBottom: '20px' },
  highlight: { background: '#EFF6FF', border: '1px solid #BFDBFE', borderRadius: '8px', padding: '16px 20px', marginBottom: '20px' },
};

export default function ShippingPolicyPage() {
  return (
    <LegalLayout title="Shipping Policy" subtitle="Last updated: April 28, 2026">
      <div style={s.page}>
        <div className="container" style={s.prose}>
          <span style={s.updated}>Effective date: April 28, 2026</span>

          <p style={s.p}>
            This policy covers two separate shipping scenarios: (1) <strong>Back2Me product orders</strong> — where we ship physical tags directly to you — and (2) <strong>Mail-It-Back</strong> — where we generate a prepaid label (prepaid by the Owner) to facilitate the return of a found item between a Finder and an Owner.
          </p>

          <div style={s.callout}>
            <strong>Important:</strong> Back2Me never handles, transports, or takes custody of found items. Mail-It-Back labels are generated by our platform and used directly between the Finder and the Owner. All carrier disputes for Mail-It-Back shipments must be directed to the carrier.
          </div>

          <hr style={s.divider} />

          <h2 style={s.h2}>1. Product Order Shipping</h2>
          <p style={s.p}>
            When you purchase a Back2Me kit, we fulfill and ship the order directly from our warehouse. Shipping is handled by FedEx, UPS, or USPS depending on your location and selected method.
          </p>

          <h3 style={s.h3}>1.1 Processing time</h3>
          <p style={s.p}>
            Orders are processed within <strong>1–2 business days</strong> of payment confirmation. Orders placed on weekends or US federal holidays are processed the next business day.
          </p>

          <h3 style={s.h3}>1.2 Domestic shipping (United States)</h3>
          <table style={s.table}>
            <thead>
              <tr>
                <th style={s.th}>Method</th>
                <th style={s.th}>Estimated Delivery</th>
                <th style={s.th}>Cost</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={s.td}>Standard Shipping</td>
                <td style={s.td}>5–7 business days</td>
                <td style={s.td}>Calculated at checkout</td>
              </tr>
              <tr>
                <td style={s.td}>Expedited Shipping</td>
                <td style={s.td}>2–3 business days</td>
                <td style={s.td}>Calculated at checkout</td>
              </tr>
              <tr>
                <td style={s.td}>Overnight</td>
                <td style={s.td}>Next business day</td>
                <td style={s.td}>Calculated at checkout</td>
              </tr>
            </tbody>
          </table>
          <p style={s.p}>
            Delivery windows are estimates and not guarantees. Carrier delays due to weather, volume, or logistics disruptions are beyond our control.
          </p>

          <h3 style={s.h3}>1.3 International shipping</h3>
          <p style={s.p}>
            We ship to most countries worldwide. International delivery typically takes <strong>7–21 business days</strong> depending on destination and customs processing. Estimated shipping costs are shown at checkout.
          </p>
          <ul style={s.ul}>
            <li style={s.li}>The customer is responsible for any import duties, taxes, or customs fees imposed by their country</li>
            <li style={s.li}>Back2Me is not responsible for delays caused by customs processing</li>
            <li style={s.li}>Some destinations may not be available at checkout — contact us at <a href="mailto:support@back2meglobal.com" style={{ color: 'var(--orange)', fontWeight: '600' }}>support@back2meglobal.com</a> if your country is not listed</li>
          </ul>

          <h3 style={s.h3}>1.4 Tracking</h3>
          <p style={s.p}>
            You will receive a shipping confirmation email with a tracking number once your order ships. Track your order via the carrier&apos;s website or from your Back2Me dashboard.
          </p>

          <h3 style={s.h3}>1.5 Lost or undelivered packages</h3>
          <p style={s.p}>
            If your tracking shows &quot;delivered&quot; but you haven&apos;t received the package, wait 24 hours and check with neighbors or your building manager. If still not found, email <a href="mailto:support@back2meglobal.com" style={{ color: 'var(--orange)', fontWeight: '600' }}>support@back2meglobal.com</a> within 7 days. We will open a carrier investigation and, if confirmed lost, send a replacement at no cost.
          </p>

          <hr style={s.divider} />

          <h2 style={s.h2}>2. Mail-It-Back (User-to-User Recovery Shipping)</h2>

          <div style={s.highlight}>
            <strong style={{ color: '#1E40AF' }}>What Mail-It-Back is:</strong>
            <p style={{ ...s.p, marginBottom: 0, marginTop: '6px', color: '#1E40AF' }}>
              Mail-It-Back is a convenience feature on the Back2Me platform. When a Finder and an Owner agree to ship a found item, Back2Me generates a prepaid carrier label (prepaid by the Owner). The Finder drops the item at a carrier location; the Owner receives it directly. Back2Me is a facilitator only — we never touch the item.
            </p>
          </div>

          <h3 style={s.h3}>2.1 How it works</h3>
          <ol style={{ paddingLeft: '20px', marginBottom: '14px' }}>
            <li style={s.li}>A scan event opens a recovery chat between the Finder and Owner</li>
            <li style={s.li}>Either party can request a Mail-It-Back label from the chat interface</li>
            <li style={s.li}>Back2Me generates a prepaid label (prepaid by the Owner) via EasyPost, with the carrier selected automatically based on origin/destination</li>
            <li style={s.li}>The Finder receives the label and drops the sealed package at any carrier location</li>
            <li style={s.li}>The Owner&apos;s address is embedded in the label but not shown in the chat — protecting privacy on both sides</li>
          </ol>

          <h3 style={s.h3}>2.2 Carrier and liability</h3>
          <ul style={s.ul}>
            <li style={s.li}>Mail-It-Back shipments are handled by third-party carriers</li>
            <li style={s.li}>Back2Me is not responsible for lost, damaged, or delayed items shipped via Mail-It-Back</li>
            <li style={s.li}>If an item is damaged in transit, the claim must be filed directly with the carrier using the tracking number provided</li>
            <li style={s.li}>Back2Me does not provide insurance for Mail-It-Back shipments unless explicitly stated at label generation</li>
          </ul>

          <h3 style={s.h3}>2.3 Misuse</h3>
          <p style={s.p}>
            Mail-It-Back labels may only be used to return a legitimately found item to its registered owner. Using a label for any other purpose is a violation of these Terms and may result in account suspension.
          </p>

          <hr style={s.divider} />

          <h2 style={s.h2}>3. Address Changes</h2>
          <p style={s.p}>
            If you need to change your shipping address after placing an order, contact <a href="mailto:support@back2meglobal.com" style={{ color: 'var(--orange)', fontWeight: '600' }}>support@back2meglobal.com</a> immediately. We can update the address if the order has not yet shipped. Once a package is with the carrier, address changes are not guaranteed.
          </p>

          <hr style={s.divider} />

          <h2 style={s.h2}>4. Contact</h2>
          <p style={s.p}>
            Shipping questions? Email <a href="mailto:support@back2meglobal.com" style={{ color: 'var(--orange)', fontWeight: '600' }}>support@back2meglobal.com</a> or visit our <Link href="/contact" style={{ color: 'var(--orange)', fontWeight: '600' }}>Contact page</Link>.
          </p>

        </div>
      </div>
    </LegalLayout>
  );
}
